apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: default
  annotations:
    load-balancer.hetzner.cloud/name: "kubernetes-load-balancer"
    load-balancer.hetzner.cloud/location: "fsn1"
    # traefik.ingress.kubernetes.io/router.entrypoints: websecure
    # cert-manager.io/issuer: "nginx-tls"
    # cert-manager.io/duration: 2160h # 90d
    # cert-manager.io/renew-before: 360h # 15d
    # cert-manager.io/cluster-issuer: "ca-issuer"
    # kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - nginx.example.com
    secretName: nginx-tls
  #ingressClassName: nginx
  rules:
  - host: nginx.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80